name: irept3
description: Reptile community.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# aos : Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# ios : https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ##################
  # Core Libraries #
  ##################

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2

  # This is a simple Service Locator for Dart and Flutter projects with some additional goodies highly inspired by Splat.
  get_it: ^7.2.0

  # InheritedWidget을 더 쉽게 사용하고 보다 재사용할 수 있도록 만들어진 래퍼입니다.
  provider: ^6.0.3

  # This plugin allows Flutter apps to discover network connectivity and configure themselves accordingly. It can distinguish between cellular vs WiFi connection.
  connectivity_plus: ^3.0.3

  # A powerful HTTP client for Dart/Flutter, which supports global configuration, interceptors, FormData, request cancellation, file uploading/downloading, timeout, and custom adapters etc.
#  dio: ^5.0.0
  dio: ^4.0.6

  # A composable, Future-based library for making HTTP requests.
  http: ^0.13.5

  # Provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0

  # Freezed tries to fix that by implementing most of this for you, allowing you to focus on the definition of your model.
#  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Wraps platform-specific persistent storage for simple data (NSUserDefaults on iOS and macOS, SharedPreferences on Android, etc.). Data may be persisted to disk asynchronously, and there is no guarantee that writes will be persisted to disk after returning, so this plugin must not be used for storing critical data.
  shared_preferences: ^2.0.18

  #################
  # UI Components #
  #################

  # For now this is limited to more than 1 tab, and less than 5. So 2-4 tabs.
  fancy_bottom_navigation: ^0.3.3

  # A carousel slider widget.
  carousel_slider: ^4.2.1

  # Provides a collection of Flutter grids layouts.
  flutter_staggered_grid_view: ^0.6.2

  # A package provides an easy way to add shimmer effect in Flutter project. shimmer : 반짝이다.
  shimmer: ^2.0.0

  # A Flutter plugin for launching a URL.
  url_launcher: ^6.1.10

  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.8.6+3

  # A Flutter plugin that provides a WebView widget.
#  webview_flutter: ^4.0.5
#  webview_flutter: ^3.0.4
#  fwfh_webview: ^0.7.0+1

  # A Flutter widget for rendering HTML and CSS as Flutter widgets.
#  flutter_html: ^2.2.1
  # Table widget for flutter_html.
  # reference : flutter_html: ^2.2.1
#  flutter_html_table: ^3.0.0-alpha.4

  # A Flutter plugin for IOS and Android providing a simple way to share a message, link or local files.
  flutter_share: ^2.0.0

  # A simple zoomable image/content widget for Flutter.
  photo_view: ^0.14.0

  # This Flutter plugin provides an API for querying information about an application package.
  package_info_plus: ^3.0.3

  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps.
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_messaging: ^14.2.5

  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^13.0.0

  # A Flutter plugin for finding commonly used locations on the filesystem.
  path_provider: ^2.0.13

  # A Flutter plugin for Google Sign In.
  google_sign_in: ^6.0.1

  # A Flutter plugin for Kakao.
#  kakao_flutter_sdk: ^1.3.1 # 전체 추가
  kakao_flutter_sdk_user: ^1.3.1 # 카카오 로그인
#  kakao_flutter_sdk_talk: ^1.3.1 # 카카오톡 메시지, 카카오톡 소셜(프로필 가져오기, 친구 목록 가져오기)
#  kakao_flutter_sdk_story: ^1.3.1 # 카카오스토리
#  kakao_flutter_sdk_share: ^1.3.1 # 카카오톡 공유
#  kakao_flutter_sdk_navi: ^1.3.1 # 카카오내비
#  kakao_flutter_sdk_friend: ^1.4.0 # 카카오톡 소셜(피커: 친구 선택하기)

  # A Flutter plugin for Apple Sign In.
  sign_in_with_apple: ^4.1.0

  # The easiest way to add facebook login to your flutter app, get user information, profile picture and more.
  flutter_facebook_auth: ^5.0.7

  # Draw SVG files using Flutter.
  flutter_svg: ^2.0.2

  # Phone Number is a Flutter plugin that allows you to parse, validate, format and other utilities for to international phone numbers.
  phone_number: ^1.0.0

  # A flutter package to select a country from a list of countries.
  country_picker: ^2.0.19

  # A flutter package which will help you to generate pin code fields with beautiful design and animations.
  pin_code_fields: ^7.4.0

  # A Flutter plugin that provides a Google Maps widget.
  google_maps_flutter: ^2.2.4

  # Google places autocomplete widgets for flutter.
  flutter_google_places: ^0.3.0

  # A Flutter Geocoding plugin which provides easy geocoding and reverse-geocoding features.
  geocoding: ^2.0.5

  # A Flutter geolocation plugin which provides easy access to platform specific location services (FusedLocationProviderClient or if not available the LocationManager on Android and CLLocationManager on iOS).
  geolocator: ^9.0.2

  # A TypeAhead (autocomplete) widget for Flutter, where you can show suggestions to users as they type
  flutter_typeahead: ^4.3.6

  # A Flutter widget that scrolls text infinitely.
  marquee: ^2.2.3

  # A simple yet fully customizable rating bar for flutter which also include a rating bar indicator, supporting any fraction of rating.
  flutter_rating_bar: ^4.0.1

  # Flutter package to render html as widgets that supports hyperlink, image, audio, video, iframe and 70+ other tags.
  flutter_widget_from_html: ^0.10.0

  # Flutter package to render html as widgets that focuses on correctness and extensibility. Supports 70+ most popular tags.
  flutter_widget_from_html_core: ^0.10.0

  # Toast Library for Flutter
  fluttertoast: ^8.2.1

  # Youtube player
  youtube_player_flutter: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  # https://dart-lang.github.io/linter/lints/index.html
  flutter_lints: ^2.0.0

  # freezed additional library
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # https://flutter.dev/assets-and-images/#resolution-aware
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/icons/
    - assets/images/
    - assets/language/
#    - assets/messages.json

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
    - family: Nanum Square
      fonts:
        - asset: assets/fonts/NanumSquareAcB.ttf
    - family: SB Aggro
      fonts:
        - asset: assets/fonts/sbaggro/SB-aggro-L.ttf
          weight: 400
        - asset: assets/fonts/sbaggro/SB-aggro-M.ttf
          weight: 500
        - asset: assets/fonts/sbaggro/SB-aggro-B.ttf
          weight: 600
